In [1]:
pip install pandas 


Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [64]:
import pandas as pd
import numpy as np
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [32]:
df = pd.read_csv("D:/Data Science Project/game platform/game_dataset.csv", encoding="ISO-8859-1")
df

sr.no                       Game Name                             Genre  \
0       1              Grand Theft Auto 5               open world,  action   
1       2              Grand Theft Auto 4               open world,  action   
2       3              Grand Theft Auto 3               open world,  action   
3       4  Grand Theft Auto: San Andrease               open world,  action   
4       5     Grand Theft Auto: Vice City               open world,  action   
5       6      Grand Theft Auto: Triology               open world,  action   
6       7                      God of War  fighting,  boss fight,  missions   
7       8                    God of War 2  fighting,  boss fight,  missions   
8       9                    God of War 3  fighting,  boss fight,  missions   
9      10    God of War: Chain Of Olympus  fighting,  boss fight,  missions   
10     11     God of War: Ghost of Sparta  fighting,  boss fight,  missions   
11     12              God of War: Revork  fighting,  boss fight,  missions   
12     13                          Ben 10  fighting,  boss fight,  missions   
13     14           Ben 10: Protect Earth  fighting,  boss fight,  missions   
14     15             Ben 10: Alian Force  fighting,  boss fight,  missions   
15     16           Ben 10: Vilgax Attack  fighting,  boss fight,  missions   
16     17             WWE Smack Down Pain                Face to face fight   
17     18                 Mortal Combat 5  fighting,  boss fight,  missions   
18     19                        Tekken 5                Face to face fight   
19     20                 Assessian Cread    fighting, boss fight, missions   
20     21                    Ghost Raider    fighting, boss fight, missions   
21     22                     Spider Man     open world,  mission, fighting   
22     23                    Spider Man 2    open world,  mission, fighting   
23     24                    Spider Man 3    open world,  mission, fighting   
24     25                Prince Of Persia  fighting,  boss fight,  missions   
25     26                      Tomb Rider       mission, level , adventures   
26     27                       Minecraft   open world crafting, creativity   
27     28                     Dragon Ball                Face to face fight   
28     29                  Ninja Guiden 3  fighting,  boss fight,  missions   
29     30   Prince Of Persia : Revelation  fighting,  boss fight,  missions   
30     31                        Tekken 6                Face to face fight   
31     32                             SSX              level , mission, fun   
32     33                  Ninja Guiden 2  fighting,  boss fight,  missions   
33     34                     Uncharted 4  fighting,  boss fight,  missions   
34     35                          Inside       mission, level , adventures   

                                          Description  \
0   GTA 5 is an open-world action-adventure game s...   
1   GTA 4 follows the story of Niko Bellic, an Eas...   
2   GTA 3 was the first 3D open-world GTA game, ch...   
3   GTA: San Andreas takes players to Los Santos, ...   
4   Set in the 1980s, GTA: Vice City follows Tommy...   
5   GTA: The Trilogy – The Definitive Edition is a...   
6   God of War is an action-adventure game series ...   
7   God of War II is an action-adventure game deve...   
8   God of War III is an action-adventure hack-and...   
9   God of War: Chains of Olympus is an action-adv...   
10  God of War: Ghost of Sparta is an action-adven...   
11  God of War: Ragnarok is an action-adventure ga...   
12  Ben 10 is an action-adventure game series base...   
13  Ben 10: Protector of Earth is an action-advent...   
14  Ben 10: Alien Force is an action-adventure gam...   
15  Ben 10: Vilgax Attacks is an action-adventure ...   
16  WWE SmackDown! Here Comes the Pain is a profes...   
17  Mortal Kombat is a legendary fighting game fra...   
18  Tekken 5 is a 3D fighting game developed and p...   
19  Assassin’s Cree

In [34]:
df.to_string

<bound method DataFrame.to_string of     sr.no                       Game Name                             Genre  \
0       1              Grand Theft Auto 5               open world,  action   
1       2              Grand Theft Auto 4               open world,  action   
2       3              Grand Theft Auto 3               open world,  action   
3       4  Grand Theft Auto: San Andrease               open world,  action   
4       5     Grand Theft Auto: Vice City               open world,  action   
5       6      Grand Theft Auto: Triology               open world,  action   
6       7                      God of War  fighting,  boss fight,  missions   
7       8                    God of War 2  fighting,  boss fight,  missions   
8       9                    God of War 3  fighting,  boss fight,  missions   
9      10    God of War: Chain Of Olympus  fighting,  boss fight,  missions   
10     11     God of War: Ghost of Sparta  fighting,  boss fight,  missions   
11     12      

In [40]:
df.head()

sr.no                       Game Name                Genre  \
0      1              Grand Theft Auto 5  open world,  action   
1      2              Grand Theft Auto 4  open world,  action   
2      3              Grand Theft Auto 3  open world,  action   
3      4  Grand Theft Auto: San Andrease  open world,  action   
4      5     Grand Theft Auto: Vice City  open world,  action   

                                         Description  \
0  GTA 5 is an open-world action-adventure game s...   
1  GTA 4 follows the story of Niko Bellic, an Eas...   
2  GTA 3 was the first 3D open-world GTA game, ch...   
3  GTA: San Andreas takes players to Los Santos, ...   
4  Set in the 1980s, GTA: Vice City follows Tommy...   

                                       Download Link  \
0  https://coolrom.com.au/roms/ps3/71044/Grand_Th...   
1  https://romsfun.com/roms/playstation-3/grand-t...   
2  https://coolrom.com.au/roms/ps2/70217/Grand_Th...   
3  https://coolrom.com.au/roms/ps2/41807/Grand_Th...   
4  https://coolrom.com.au/roms/ps2/70195/Grand_Th...   

                                   Profile Image URL  
0    D:\Data Science Project\game platform\gta 5.jpg  
1    D:\Data Science Project\game platform\gta 4.jpg  
2     D:\Data Science Project\game platform\gta3.jpg  
3  D:\Data Science Project\game platform\gta san.jpg  
4  D:\Data Science Project\game platform\gta vice...

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   sr.no              35 non-null     int64 
 1   Game Name          35 non-null     object
 2   Genre              35 non-null     object
 3   Description        35 non-null     object
 4   Download Link      35 non-null     object
 5   Profile Image URL  35 non-null     object
dtypes: int64(1), object(5)
memory usage: 1.8+ KB


In [44]:
df.describe()

sr.no
count  35.000000
mean   18.000000
std    10.246951
min     1.000000
25%     9.500000
50%    18.000000
75%    26.500000
max    35.000000

In [46]:
u=df.isnull().sum()
u

sr.no                0
Game Name            0
Genre                0
Description          0
Download Link        0
Profile Image URL    0
dtype: int64

In [48]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
dtype: bool

In [52]:
df.shape

(35, 6)

In [54]:
selected_feature = ['Genre', 'Description']

print(selected_feature)

['Genre', 'Description']


In [56]:
for feature in selected_feature:
    df[feature] = df[feature].fillna('')

In [58]:
combined_feature = df['Genre']

In [60]:
print(combined_feature)

0                  open world,  action
1                  open world,  action
2                  open world,  action
3                  open world,  action
4                  open world,  action
5                  open world,  action
6     fighting,  boss fight,  missions
7     fighting,  boss fight,  missions
8     fighting,  boss fight,  missions
9     fighting,  boss fight,  missions
10    fighting,  boss fight,  missions
11    fighting,  boss fight,  missions
12    fighting,  boss fight,  missions
13    fighting,  boss fight,  missions
14    fighting,  boss fight,  missions
15    fighting,  boss fight,  missions
16                  Face to face fight
17    fighting,  boss fight,  missions
18                  Face to face fight
19      fighting, boss fight, missions
20      fighting, boss fight, missions
21      open world,  mission, fighting
22      open world,  mission, fighting
23      open world,  mission, fighting
24    fighting,  boss fight,  missions
25         mission, level

In [66]:
vectorizer = TfidfVectorizer()

In [68]:
feature_vector = vectorizer.fit_transform(combined_feature)

In [70]:
print(feature_vector)

  (0, 12)	0.5378860129075845
  (0, 14)	0.5378860129075845
  (0, 0)	0.6491203850109498
  (1, 12)	0.5378860129075845
  (1, 14)	0.5378860129075845
  (1, 0)	0.6491203850109498
  (2, 12)	0.5378860129075845
  (2, 14)	0.5378860129075845
  (2, 0)	0.6491203850109498
  (3, 12)	0.5378860129075845
  (3, 14)	0.5378860129075845
  (3, 0)	0.6491203850109498
  (4, 12)	0.5378860129075845
  (4, 14)	0.5378860129075845
  (4, 0)	0.6491203850109498
  (5, 12)	0.5378860129075845
  (5, 14)	0.5378860129075845
  (5, 0)	0.6491203850109498
  (6, 7)	0.47926886657127055
  (6, 2)	0.5263466474361039
  (6, 6)	0.46499437308534947
  (6, 11)	0.5263466474361039
  (7, 7)	0.47926886657127055
  (7, 2)	0.5263466474361039
  (7, 6)	0.46499437308534947
  :	:
  (28, 7)	0.47926886657127055
  (28, 2)	0.5263466474361039
  (28, 6)	0.46499437308534947
  (28, 11)	0.5263466474361039
  (29, 7)	0.47926886657127055
  (29, 2)	0.5263466474361039
  (29, 6)	0.46499437308534947
  (29, 11)	0.5263466474361039
  (30, 6)	0.2127549510723282
  (30, 5)	

In [74]:
similarity = cosine_similarity(feature_vector)

In [80]:
feature_vector

<35x15 sparse matrix of type '<class 'numpy.float64'>'
	with 127 stored elements in Compressed Sparse Row format>

In [82]:
print(similarity)

[[1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [84]:
print(similarity.shape)

(35, 35)


In [86]:
Game_Name = input("Enter The Game Name:")

Enter The Game Name: God of War


In [90]:
list_of_all_titles = df['Game Name'].tolist()
print(list_of_all_titles)

['Grand Theft Auto 5', 'Grand Theft Auto 4', 'Grand Theft Auto 3', 'Grand Theft Auto: San Andrease', 'Grand Theft Auto: Vice City', 'Grand Theft Auto: Triology', 'God of War', 'God of War 2', 'God of War 3', 'God of War: Chain Of Olympus', 'God of War: Ghost of Sparta', 'God of War: Revork', 'Ben 10', 'Ben 10: Protect Earth', 'Ben 10: Alian Force', 'Ben 10: Vilgax Attack', 'WWE Smack Down Pain', 'Mortal Combat 5', 'Tekken 5', 'Assessian Cread', 'Ghost Raider', 'Spider Man ', 'Spider Man 2', 'Spider Man 3', 'Prince Of Persia', 'Tomb Rider', 'Minecraft', 'Dragon Ball', 'Ninja Guiden 3', 'Prince Of Persia : Revelation', 'Tekken 6', 'SSX', 'Ninja Guiden 2', 'Uncharted 4', 'Inside']


In [92]:
find_close_match = difflib.get_close_matches(Game_Name,list_of_all_titles)
print(find_close_match)

['God of War', 'God of War 3', 'God of War 2']


In [94]:
close_match = find_close_match[0]
print(close_match)

God of War


In [121]:
df.rename(columns={'Game Name': 'Name'}, inplace=True)

In [123]:
df.head()

sr.no                            Name                Genre  \
0      1              Grand Theft Auto 5  open world,  action   
1      2              Grand Theft Auto 4  open world,  action   
2      3              Grand Theft Auto 3  open world,  action   
3      4  Grand Theft Auto: San Andrease  open world,  action   
4      5     Grand Theft Auto: Vice City  open world,  action   

                                         Description  \
0  GTA 5 is an open-world action-adventure game s...   
1  GTA 4 follows the story of Niko Bellic, an Eas...   
2  GTA 3 was the first 3D open-world GTA game, ch...   
3  GTA: San Andreas takes players to Los Santos, ...   
4  Set in the 1980s, GTA: Vice City follows Tommy...   

                                       Download Link  \
0  https://coolrom.com.au/roms/ps3/71044/Grand_Th...   
1  https://romsfun.com/roms/playstation-3/grand-t...   
2  https://coolrom.com.au/roms/ps2/70217/Grand_Th...   
3  https://coolrom.com.au/roms/ps2/41807/Grand_Th...   
4  https://coolrom.com.au/roms/ps2/70195/Grand_Th...   

                                   Profile Image URL  
0    D:\Data Science Project\game platform\gta 5.jpg  
1    D:\Data Science Project\game platform\gta 4.jpg  
2     D:\Data Science Project\game platform\gta3.jpg  
3  D:\Data Science Project\game platform\gta san.jpg  
4  D:\Data Science Project\game platform\gta vice...

In [127]:
index_of_the_game = df[df.Name == close_match]['sr.no'].values[0]
print(index_of_the_game)

7


In [129]:
similarity_score = list(enumerate(similarity[index_of_the_game]))
print(similarity_score)

[(0, 0.0), (1, 0.0), (2, 0.0), (3, 0.0), (4, 0.0), (5, 0.0), (6, 1.0), (7, 1.0), (8, 1.0), (9, 1.0), (10, 1.0), (11, 1.0), (12, 1.0), (13, 1.0), (14, 1.0), (15, 1.0), (16, 0.09892985509468145), (17, 1.0), (18, 0.09892985509468145), (19, 1.0), (20, 1.0), (21, 0.16524214950807498), (22, 0.16524214950807498), (23, 0.16524214950807498), (24, 1.0), (25, 0.0), (26, 0.0), (27, 0.09892985509468145), (28, 1.0), (29, 1.0), (30, 0.09892985509468145), (31, 0.0), (32, 1.0), (33, 1.0), (34, 0.0)]


In [131]:
len(similarity_score)

35

In [133]:
sorted_similar_game = sorted (similarity_score, key=lambda x:x[1],reverse = True)
print(sorted_similar_game)

[(6, 1.0), (7, 1.0), (8, 1.0), (9, 1.0), (10, 1.0), (11, 1.0), (12, 1.0), (13, 1.0), (14, 1.0), (15, 1.0), (17, 1.0), (19, 1.0), (20, 1.0), (24, 1.0), (28, 1.0), (29, 1.0), (32, 1.0), (33, 1.0), (21, 0.16524214950807498), (22, 0.16524214950807498), (23, 0.16524214950807498), (16, 0.09892985509468145), (18, 0.09892985509468145), (27, 0.09892985509468145), (30, 0.09892985509468145), (0, 0.0), (1, 0.0), (2, 0.0), (3, 0.0), (4, 0.0), (5, 0.0), (25, 0.0), (26, 0.0), (31, 0.0), (34, 0.0)]


In [137]:
print('Games Suggested For You: \n')

i = 1
for game in sorted_similar_game:
    index = game[0]
    title_from_index = df[df.index==index]['Name'].values[0]
    if(i<11):
        print(i,'.',title_from_index)
        i+=1

Games Suggested For You: 

1 . God of War
2 . God of War 2
3 . God of War 3
4 . God of War: Chain Of Olympus
5 . God of War: Ghost of Sparta
6 . God of War: Revork
7 . Ben 10
8 . Ben 10: Protect Earth
9 . Ben 10: Alian Force
10 . Ben 10: Vilgax Attack


In [141]:
Game_Name = input("Enter The Game Name:")
list_of_all_titles = df['Name'].tolist()
find_close_match = difflib.get_close_matches(Game_Name,list_of_all_titles)
close_match = find_close_match[0]
index_of_the_game = df[df.Name == close_match]['sr.no'].values[0]
similarity_score = list(enumerate(similarity[index_of_the_game]))
sorted_similar_game = sorted (similarity_score, key=lambda x:x[1],reverse = True)
print('Games Suggested For You: \n')

i = 1
for game in sorted_similar_game:
    index = game[0]
    title_from_index = df[df.index==index]['Name'].values[0]
    if(i<11):
        print(i,'.',title_from_index)
        i+=1

Enter The Game Name: Spider man


Games Suggested For You: 

1 . Spider Man 
2 . Spider Man 2
3 . Spider Man 3
4 . Grand Theft Auto 5
5 . Grand Theft Auto 4
6 . Grand Theft Auto 3
7 . Grand Theft Auto: San Andrease
8 . Grand Theft Auto: Vice City
9 . Grand Theft Auto: Triology
10 . Minecraft
